CREATE DATABASE MY_PROJECT
USE MY_PROJECT
GO
CREATE TABLE USER_DATA(
ID_USER CHAR(10) NOT NULL, --mã người dùng
NAME_USER NCHAR(20) NOT NULL, --tên người dùng
USER_PASSWORD CHAR(64) not null, --mật khẩu
DAY_CREATED DATE, --ngày tạo
USER_ADDRESS NCHAR(50), --địa chỉ
USER_TYPE CHAR(20), --loại tài khoản
USER_STATUS CHAR(20), --trạng thái
EMAIL CHAR(50), --địa chỉ email
PROFILE_PICTURE char(50), -- đường dẫn ảnh đại diện
CONSTRAINT PK_USER PRIMARY KEY (ID_USER),
)

--Tạo bảng loại sanr phẩm
CREATE TABLE LOAISP(
ID_LOAI CHAR(10) NOT NULL,
TENLOAI NCHAR(50),
CONSTRAINT PK_LOAI PRIMARY KEY (ID_LOAI))
--Tạo bảng sản Phẩm
CREATE TABLE SANPHAM(
ID_SANPHAM CHAR(10) NOT NULL,
TENSP NCHAR(50),
MOTA NCHAR(300),
HINHANH CHAR(50),
ID_LOAI CHAR(10) NOT NULL,
GIA_BAN FLOAT,
SL_TON INT,
XUAT_XU NCHAR(50),
CONSTRAINT PK_SANPHAM PRIMARY KEY (ID_SANPHAM),
CONSTRAINT FK_SANPHAM_LOAIHANG FOREIGN KEY (ID_LOAI) REFERENCES LOAISP(ID_LOAI))
--DANH SACH KHU VUC
CREATE TABLE KHUVUC(
MAKV CHAR(10) NOT NULL,
TENKV NCHAR(50),
CONSTRAINT PK_KHUVUC PRIMARY KEY (MAKV))
--DANH SACH CUA HANG
CREATE TABLE CUAHANG(
MACH CHAR(10) NOT NULL,
TENCH NCHAR(50),
DIACHI NCHAR(50),
MAKV CHAR(10) NOT NULL,
ID_SANPHAM CHAR(10) NOT NULL,
SLTON INT,
CONSTRAINT PK_CUAHANG PRIMARY KEY (MACH),
CONSTRAINT FK_CUAHANG_SANPHAM FOREIGN KEY (ID_SANPHAM) REFERENCES SANPHAM(ID_SANPHAM),
CONSTRAINT FK_CUAHANG_KHUVUC FOREIGN KEY (MAKV) REFERENCES KHUVUC(MAKV))
--DANH SACH VOUCHER
CREATE TABLE VOUCHER(
ID_VOUCHER CHAR(20) NOT NULL,
TENVC NCHAR(50),
GIATRI INT,
DIEUKIEN NCHAR(50),
CONSTRAINT PK_VOUCHER PRIMARY KEY (ID_VOUCHER))
--Tạo bảng đơn hàng
CREATE TABLE DONHANG(
ID_USER CHAR(10) NOT NULL,
ID_DONHANG CHAR(10) NOT NULL,
ID_SANPHAM CHAR(10) NOT NULL,
ID_VOUCHER CHAR(10) NOT NULL,
CONSTRAINT PK_DONHANG PRIMARY KEY (ID_DONHANG),
CONSTRAINT FK_DONHANG_SANPHAM FOREIGN KEY (ID_SANPHAM) REFERENCES SANPHAM(ID_SANPHAM),
CONSTRAINT FK_DONHANG_USER foreign key (ID_USER) REFERENCES USER_DATA(ID_USER),
CONSTRAINT FK_DONHANG_VOUCHER foreign key (ID_VOUCHER) REFERENCES VOUCHER(ID_VOUCHER)
)
--Tạo bảng hóa đơn
CREATE TABLE HOA_DON(
ID_DONHANG char(10) not null,
THANH_TIEN FLOAT,
PT_THANHTOAN NCHAR(50),
DAYCREATE DATE,
ID_HOADON CHAR(10) NOT NULL,
CONSTRAINT PK_HOADON PRIMARY KEY (ID_HOADON),
CONSTRAINT FK_HOADON_DONHANG foreign key (ID_DONHANG) REFERENCES DONHANG(ID_DONHANG)
)
--DANH SACH SUA DOI
CREATE TABLE LICH_SU_SUA_DOI(
ID_USER CHAR(10) NOT NULL,
ID_SANPHAM CHAR(10) NOT NULL,
NOTE NCHAR(50),
GIATRICU NCHAR(50),
GIATRIMOI NCHAR(50),
ID_SUA_DOI CHAR(10) NOT NULL,
CONSTRAINT PK_SUADOI PRIMARY KEY (ID_SUA_DOI),
CONSTRAINT FK_SUADOI_USER FOREIGN KEY (ID_USER) REFERENCES USER_DATA(ID_USER),
CONSTRAINT FK_SUADOI_SANPHAM FOREIGN KEY (ID_SANPHAM) REFERENCES SANPHAM(ID_SANPHAM))
--DANH SACH NHAP HANG
CREATE TABLE NHAPHANG(
ID_USER CHAR(10) NOT NULL,
ID_NHAPHANG CHAR(10) NOT NULL,
ID_SANPHAM CHAR(10) NOT NULL,
SL INT,
NGAY_NH DATE,
CONSTRAINT PK_NHAPHANG PRIMARY KEY (ID_NHAPHANG),
CONSTRAINT FK_NHAPHANG_USER FOREIGN KEY (ID_USER) REFERENCES USER_DATA(ID_USER),
CONSTRAINT FK_NHAPHANG_SANPHAM FOREIGN KEY (ID_SANPHAM) REFERENCES SANPHAM(ID_SANPHAM))
INSERT INTO USER_DATA VALUES('USER00O001','ADMIN','Amkiso2019@','2025/01/01','NO ADDRESS','ADMINISTRATOR','ACTIVE','Thangcuoi1984a@gmail.com','ADMIN.JPG')
INSERT INTO LOAISP VALUES
('DT001',N'LAPTOP'),
('DT002',N'Điện thoại'),
('DT003',N'Phụ kiện'),
('DT004',N'Đồng hồ'),
('DT005',N'SmartWatch'),
('DT006',N'Tablet'),
('DT007',N'PC, Thiết bị văn phòng'),
('DT008',N'Máy cũ');
INSERT INTO KHUVUC VALUES
('KV001','Hồ Chí Minh'),
('KV002','Hà Nội'),
('KV003','Đà Nẵng');
insert into CUAHANG values
('Mã cửa hàng','Tên cửa hàng', 'Địa chỉ','Mã khu vực','ID sản phẩm','Số lượng tồn'),
('','','','','',''),
('','','','','',''),
('','','','','',''),
('','','','','',''),
('','','','','',''),
('','','','','',''),
('','','','','',''),
('','','','','',''),
('','','','','',''),
('','','','','',''),
('','','','','',''),
('','','','','','');